"""Model training utilities for F1 deviation classification."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List

import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from feature_engineering import engineer_features
from preprocessing import build_preprocessor, encode_target, preprocess_for_modeling


RANDOM_STATE = 42


@dataclass
class TrainingArtifacts:
    """Container with all objects generated by training."""

    models: Dict[str, Pipeline]
    X_train: pd.DataFrame
    X_test: pd.DataFrame
    y_train: np.ndarray
    y_test: np.ndarray
    label_encoder: object
    categorical_cols: List[str]
    numerical_cols: List[str]


def build_classifiers(random_state: int = RANDOM_STATE) -> Dict[str, BaseEstimator]:
    """Create baseline classifiers required by the project."""
    return {
        "Logistic Regression": LogisticRegression(max_iter=2000, random_state=random_state),
        "SVM": SVC(C=1.0, kernel="rbf", probability=True, random_state=random_state),
        "Decision Tree": DecisionTreeClassifier(random_state=random_state),
        "Random Forest": RandomForestClassifier(
            n_estimators=400,
            random_state=random_state,
            n_jobs=-1,
        ),
        "Naive Bayes": GaussianNB(),
        "MLP": MLPClassifier(
            hidden_layer_sizes=(64, 32),
            max_iter=800,
            random_state=random_state,
        ),
    }


def build_model_pipelines(
    categorical_cols: List[str],
    numerical_cols: List[str],
    random_state: int = RANDOM_STATE,
) -> Dict[str, Pipeline]:
    """Build separate preprocessing + model pipelines for each classifier."""
    classifiers = build_classifiers(random_state=random_state)
    pipelines: Dict[str, Pipeline] = {}

    for model_name, estimator in classifiers.items():
        preprocessor = build_preprocessor(categorical_cols, numerical_cols)
        pipelines[model_name] = Pipeline(
            steps=[
                ("preprocessor", preprocessor),
                ("model", estimator),
            ]
        )

    return pipelines


def train_models(pipelines: Dict[str, Pipeline], X_train: pd.DataFrame, y_train: np.ndarray) -> Dict[str, Pipeline]:
    """Fit all model pipelines."""
    trained_models: Dict[str, Pipeline] = {}

    for model_name, pipeline in pipelines.items():
        pipeline.fit(X_train, y_train)
        trained_models[model_name] = pipeline

    return trained_models


def train_all_models(
    raw_dataframe: pd.DataFrame,
    test_size: float = 0.2,
    dnf_strategy: str = "mark",
    rolling_window: int = 5,
    random_state: int = RANDOM_STATE,
) -> TrainingArtifacts:
    """Run feature engineering, preprocessing, split, and model training."""
    featured_df = engineer_features(raw_dataframe, rolling_window=rolling_window)
    prepared_df, categorical_cols, numerical_cols = preprocess_for_modeling(featured_df, dnf_strategy=dnf_strategy)

    feature_cols = categorical_cols + numerical_cols
    X = prepared_df[feature_cols].copy()
    y, label_encoder = encode_target(prepared_df["class_label"])

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=test_size,
        random_state=random_state,
        stratify=y,
    )

    pipelines = build_model_pipelines(
        categorical_cols=categorical_cols,
        numerical_cols=numerical_cols,
        random_state=random_state,
    )
    trained_models = train_models(pipelines, X_train, y_train)

    return TrainingArtifacts(
        models=trained_models,
        X_train=X_train,
        X_test=X_test,
        y_train=y_train,
        y_test=y_test,
        label_encoder=label_encoder,
        categorical_cols=categorical_cols,
        numerical_cols=numerical_cols,
    )


if __name__ == "__main__":
    data = pd.read_csv("f1_deviation_dataset_2022_2024.csv")
    artifacts = train_all_models(data)
    print("Trained models:", list(artifacts.models.keys()))
    print("Train shape:", artifacts.X_train.shape)
    print("Test shape:", artifacts.X_test.shape)
